# ai-test-generator/generators/test_assembler.py

import os

class TestAssembler:
    """
    Assembles final test files by combining AI-generated content with static templates.
    """

    def __init__(self, template_dir: str):
        """
        :param template_dir: Directory containing framework-specific test templates.
        """
        self.template_dir = template_dir

    def load_template(self, framework: str, template_name: str = "default") -> str:
        """
        Loads a template for the specified framework.
        
        :param framework: The framework name (e.g., 'pytest', 'jest').
        :param template_name: The template file base name (without extension).
        :return: Template content as a string.
        """
        template_path = os.path.join(self.template_dir, framework, f"{template_name}.txt")
        if not os.path.exists(template_path):
            raise FileNotFoundError(f"Template not found: {template_path}")
        with open(template_path, "r", encoding="utf-8") as f:
            return f.read()

    def assemble_tests(self, framework: str, ai_generated_tests: str, output_path: str) -> None:
        """
        Combines the AI-generated tests with the static template and writes the final test file.
        
        :param framework: The target test framework.
        :param ai_generated_tests: The tests generated by the AI.
        :param output_path: Path where the assembled test file should be saved.
        """
        try:
            template_content = self.load_template(framework)
            # Assume the template contains a placeholder {generated_tests}
            final_test_content = template_content.format(generated_tests=ai_generated_tests)
            with open(output_path, "w", encoding="utf-8") as f:
                f.write(final_test_content)
            print(f"Final test file assembled at: {output_path}")
        except Exception as e:
            raise RuntimeError(f"Failed to assemble test file: {e}") from e


# --- Example Usage ---
# if __name__ == "__main__":
#     assembler = TestAssembler(template_dir="ai-test-generator/templates/framework")
#     ai_tests = "def test_example():\n    assert True"
#     assembler.assemble_tests(framework="pytest", ai_generated_tests=ai_tests, output_path="assembled_test.py")
